# Generated by Django 3.2.3 on 2022-12-18 08:58

from django.db import migrations, models
import siteweb.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_AO', models.CharField(max_length=15)),
                ('date_publication', models.DateField()),
                ('categorie', models.CharField(choices=[('services', 'Services'), ('travaux', 'Travaux'), ('fournitures', 'Fournitures')], default='services', max_length=15)),
                ('objet', models.CharField(max_length=100)),
                ('lieu_execution', models.CharField(max_length=15)),
                ('date_limite_remise', models.DateField()),
                ('date_ouverture', models.DateField()),
                ('avis_pdf', models.FileField(default=None, upload_to='ao/', validators=[siteweb.validators.validate_file_extension])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('delai_archivage', models.PositiveIntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateField()),
                ('date_limite_candidature', models.DateField()),
                ('date_concours', models.DateField()),
                ('fonction', models.CharField(max_length=15)),
                ('type_contrat', models.CharField(choices=[('cdd', 'CDD'), ('cdi', 'CDI')], default='cdd', max_length=15)),
                ('nombre_poste', models.PositiveIntegerField(default=10)),
                ('avis_pdf', models.FileField(default=None, upload_to='recrutement/', validators=[siteweb.validators.validate_file_extension])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('delai_archivage', models.PositiveIntegerField(default=90)),
            ],
        ),
    ]
