# Generated by Django 3.2.3 on 2022-12-18 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeloffre',
            name='delai_archivage',
        ),
        migrations.RemoveField(
            model_name='recrutement',
            name='delai_archivage',
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_archivage',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='recrutement',
            name='date_archivage',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='numero_AO',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
