# Generated by Django 3.2.3 on 2022-12-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_alter_appeloffre_date_archivage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='date_publication',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='recrutement',
            name='date_archivage',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recrutement',
            name='date_publication',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
